### ISSUE TITLE
Error when creating new solution from the template

### ISSUE THREAD

**Issue by luedi** [dnikolovv/devadventures-net-core-template#2]
I just tried to create a new solution from your template and got the following error:

![devenv_2018-08-25_13-50-37](https://user-images.githubusercontent.com/12098314/44618090-c6815100-a86f-11e8-9da5-6ad93825741a.png)

After closing the message box i see an error in Business test Project:

![image](https://user-images.githubusercontent.com/12098314/44618111-195b0880-a870-11e8-947f-dd9e4b1c27ba.png)

I tried to build the solution, but i got a bunch of compile Errors (283 to be precise). Next i fixed the broken project reference in the test project. When i have done this some errors remains:

![image](https://user-images.githubusercontent.com/12098314/44618197-dc901100-a871-11e8-87df-773f67d200fc.png)

I took a look at the solution with the Windows Explorer and noticed that the folder configuration and the file stylecop.json is missing. After removing the references to stylecop.json in the projects i could successfully compile the solution.

**Comment by dnikolovv** [comment]
Hm... I seem to be unable to reproduce this.

I also asked a few friends to try and it worked straight out of the box for them.

It seems to me that this may be a Windows path length issue. Consider using a shorter root path for the project (ex. C:\Test\). Also make sure that you're running the latest version (1.3) of the extension.

**Comment by luedi** [comment]
I have investigated the problem further. First i thought it maybe occurs because i use the Resharper extension, which does heavy code analysis. But this is not the case. Also if i disable it, the problem occurs.

If i start a new instance of Visual studio (i'm using 15.8.1 Community) i can create a new solution from the template successfully. But every subsequent create will fail until i close VS and reopen it again. This behavoir is perfectly reproducable. I'm using a short path as you suggested (F:\Test) and also a short solution name. Even if i create a new blank solution and add a new project using the template the errors will occur.

Also the file layout seems to be broken. Take a look at the Directory structure below. The "Test" Folder is a successfully created solution. The "Test1" Folder is a broken solution:

![image](https://user-images.githubusercontent.com/12098314/44735979-3c92eb80-aaee-11e8-8b10-6be586139c2e.png)

If you need any further information, let me know.

**Comment by dnikolovv** [comment]
Thank you! I will be reviewing this bug and update you when it's fixed.

**Comment by dnikolovv** [comment]
Hey,

I tried to reproduce the issue again, but unfortunately I'm unable to.

![image](https://user-images.githubusercontent.com/18270328/44944385-71e55500-adde-11e8-9617-f229415fdb50.png)

I made 5 subsequent projects and all were generated successfully. (using VS 15.8.1 Professional)

When I have some more free time available I'll clean up and open source the extension code itself. That will enable you to debug it on your system. Until then, I'm not sure if there's anything we can do.

Thank you

**Comment by dnikolovv** [comment]
@luedi Hey! I've open sourced the extension code. You can debug it locally if you want.

**Comment by luedi** [comment]
Good news...
I never created an extension. It would be nice if you could provide a short description on how to setup the solution (e.g what prerequisites have to be instlled).

Regards
Klaus

**Comment by luedi** [comment]
Just tried the latest version of your extension in VS 2018.9 Preview 3. The bug seems to be fixed, got no errors and the solution is created as expected.

Regards
Klaus
