### ISSUE TITLE
Are there any apps in GitHub that was built using this template?

### ISSUE THREAD

**Issue by abukres** [dnikolovv/devadventures-net-core-template#3]

**Comment by dnikolovv** [comment]
Hey,

At the moment I'm not aware of any open-source applications using the template.

There's a [realworld](https://github.com/gothinkster/realworld) back-end currently in the works, which I suspect will take no more than a week to be completed.

I'll post a link of it once I submit a PR.

**Comment by dnikolovv** [comment]
Hey there.

I have uploaded the realworld project to github and created an issue.

You can take a look at it [here](https://github.com/gothinkster/realworld/issues/270).

**Comment by abukres** [comment]
Thanks for posting it.
